# Generated by Django 6.0 on 2025-12-29 07:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='project_image'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='service_image'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='client_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='testimonial_image'),
        ),
    ]
